### ISSUE TITLE
long file name issue while cloning the project on windows machine

### ISSUE THREAD

**Issue by narahari92** [Impetus/fabric-jdbc-connector#2]
When cloning the project on windows machine many files ending with "_sk" under _src/test/resources/blockchain-query_ folder which are used in integration tests doesn't download because of exceeding max file name length of windows os and as a result ```git clone``` fails.

This issue can be fixed by renaming the files to shorter file name.

**Comment by ashishkshukla** [comment]
Issue is fixed.
